import React, { Component } from "react";
import type { NextPage } from 'next'
import Slider from "react-slick";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CenterMode from "../components/CenterSlider";
import SimpleSlider from "../components/CenterSlider";
import Navbar from "../components/Navbar"
import CenterSlider from "../components/CenterSlider";
import { motion } from 'framer-motion';


const Coming: NextPage = () => {
    const settings = {
        className: "center",
        centerMode: true,
        infinite: true,
        centerPadding: "60px",
        slidesToShow: 3,
        speed: 500
    };
  return (
    <div className={styles.container}>
      <Head>
        <title>COMING SOON</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
          <link
              rel="preload"
              href="/fonts/Danger/Another%20Danger%20Slanted.woff"
              as="font"
              crossOrigin=""
          />
          <link
              rel="preload"
              href="/fonts/Jost/Jost-Black.woff"
              as="font"
              crossOrigin=""
          />
      </Head>

      <main className={styles.main}>

          <Navbar></Navbar>

          {/*TAVERNA*/}

          <div className={' block bg-cover text-[10px] sm:text-[25px] lg:text-[30px] bg-[url(../public/images/coming_soon.png)] relative w-[100vw] h-[58vw]'}>
              <motion.div className={'absolute top-0'} initial={'hidden'} animate={'visible'} variants={{
                  'hidden': {
                      opacity: 0
                  },
                  'visible': {
                      opacity: 1,
                      transition: {
                          delay: .4,
                          duration:1,
                      },
                  },
              }}><h1 className={'top-[22vw] text-center absolute inline-block left-[36vw] top-[4vw] text-reon text-[9vw] w-[50vw] font-title'}>COMING SOON</h1></motion.div>
              <motion.div className={'z-50 cursor-pointer inline-block absolute left-[23.8vw] top-[6.4vw] w-[5.3vw] h-[5.3vw]  rotate-180'} initial={'hidden'} animate={'visible'} variants={{
                  'hidden':{
                      opacity:0,
                  },
                  'visible':{
                      opacity:1,
                      transition:{
                          delay:0.5,
                          ease:'circIn',
                          duration:0.3,
                      }
                  }}}><a className={'cursor-pointer'} href={'/'}><Image className={'rotate-180 cursor-pointer'} src={'/images/goback_arrow.png'} layout={'fill'} /></a></motion.div>
          </div>


      </main>

        <footer>
            <div className={'w-full h-[12vw]'}>
                <div className={'w-[73%] left-[21%] top-[-2vw] relative h-full'}>
                    <div className={'inline-block w-[8.5vw] h-[8.5vw] absolute top-[30%] left-0'}>
                        <Image src={'/images/footer_logo.png'} layout={'fill'}></Image>
                    </div>
                    <a className={'tracking-[0.135em] font-title text-[1.5vw] top-[6.6vw] absolute text-reon left-[11vw]'} href={'/'}>MAIN</a>
                    <a className={'tracking-[0.135em] font-title text-[1.5vw] top-[6.6vw] absolute text-reon left-[17.5vw]'} href={'/arena'}>ARENA</a>
                    <a className={'tracking-[0.135em] font-title text-[1.5vw] top-[6.6vw] absolute text-reon left-[25.6vw]'} href={'/marketplace'}>MARKETPLACE</a>
                    <a className={'tracking-[0.135em] font-title text-[1.5vw] top-[6.6vw] absolute text-reon left-[39.6vw]'} href={'/tavern'}>TAVERN</a>
                    <a className={'tracking-[0.135em] font-title text-[1.5vw] top-[6.6vw] absolute text-reon left-[48.6vw]'} href={'/coming'}>MY ACCOUNT</a>
                    <div className={'inline-block absolute top-[6vw] left-[64.6vw] w-[3.6vw] h-[3.6vw]'}>
                        <Image src={'/images/twitter_button.png'} layout={'fill'}></Image>
                    </div>
                    <div className={'inline-block absolute top-[6vw] left-[68.9vw] w-[3.6vw] h-[3.6vw]'}>
                        <Image src={'/images/telegram_button.png'} layout={'fill'}></Image>
                    </div>
                    <div className={'inline-block absolute top-[6vw] left-[60.3vw] w-[3.6vw] h-[3.6vw]'}>
                        <Image src={'/images/mail_button.png'} layout={'fill'}></Image>
                    </div>
                </div>
            </div>

        </footer>
    </div>
  )
}

export default Coming
