import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
          <link
              rel="preload"
              href="/fonts/Danger/Another%20Danger%20Slanted.woff"
              as="font"
              crossOrigin=""
          />
          <link
              rel="preload"
              href="/fonts/Jost/Jost-Black.woff"
              as="font"
              crossOrigin=""
          />
      </Head>

      <main className={styles.main}>

          {/*INTRO*/}

          <div className={'overflow-auto block bg-cover text-[10px] top-[1px] sm:text-[25px] lg:text-[30px] bg-[url(../public/images/bg_1.png)] relative w-[100vw] h-[58vw]'}>
              <h1 className={'absolute inline-block left-[30vw] top-[20vw] text-reon text-[9vw] font-title'}><span className={'text-[12vw]'}>R</span>EO<span className={'text-[12vw]'}>N</span></h1>
              <h3 className={'absolute inline-block font-desc text-white left-[56vw] top-[26vw] leading-[123%] w-[27vw] text-[1.7vw]'}>From gamers and for gamers.
                  We promise you a new experience in GameFi</h3>
              <h3 className={'absolute inline-block tracking-[0.13em] font-title text-white text-center left-[34.3vw] top-[34vw] leading-[123%] w-[42vw] text-[2.75vw]'}>Reincarnation of nation</h3>
              <div className={'inline-block relative left-[23.8vw] top-[39.3vw] w-[21.7vw] h-[5.8vw]'}><Image src={'/images/blade.png'} layout={'fill'} /></div>
              <div className={'inline-block relative left-[40.4vw] top-[39.3vw] w-[21.7vw] h-[5.8vw]'}><Image className={'rotate-180'} src={'/images/blade.png'} layout={'fill'} /></div>
              <button className={'rounded-[1vw] absolute left-[39.6vw] h-[7.2vw] w-[29.2vw] top-[39vw] gold-button'}><h2 className={'button-text font-title tracking-[0.13em] text-[3.5vw]'}>LEARN MORE</h2></button>
              <div className={'inline-block absolute left-[37.7vw] bottom-[1vw] w-[31.6vw] h-[2vw]'}><Image className={'rotate-180'} src={'/images/uzor.png'} layout={'fill'} /></div>
          </div>


          {/*ABOUT*/}

          <div className={'block bg-cover text-[10px] sm:text-[25px] lg:text-[30px] bg-[url(../public/images/bg_2.png)] relative w-[100vw] h-[61vw]'}>
              <div className={'inline-block absolute right-0 top-[3.5vw] w-[20.4vw] h-[35.6vw]'}><Image src={'/images/sekira.png'} layout={'fill'} /></div>
              <h3 className={'absolute inline-block font-desc text-white left-[27.7vw] top-[8.2vw] leading-[127%] w-[38vw] text-[1.6vw]'}>ReoN is a turn-based PVP multiplayer RPG with a very detailed and elaborated internal and external economy. Immerse yourself in the ramified history of the world ReoN,
                  pump and develop your character, feel the atmosphere of clan confrontations and sharpen the coolest equipment on the server</h3>
              <h1 className={'absolute inline-block right-[12.6vw] top-[6.7vw] text-reon text-[9.6vw] font-title'}>ABOUT</h1>
              <div className={'inline-block absolute w-[8vw] h-[8vw] left-[25vw] top-[18vw]'}>
                  <Image src={'/images/goldframe.svg'} layout={'fill'}></Image>
              </div>
              <div className={'absolute blur-shape rounded-[0.4vw] left-[23vw] top-[32.4vw] w-[22.8vw] h-[7.5vw]'}>
                  <p className={'z-40 text-[1.4vw] text-center p-[1.7vw] absolute top-0 text-white font-desc font-light'}>Purchase the starter pack with characters and items</p>
                  {/*<Image src={'/images/AboutScreenShapes/1.svg'} layout={'fill'} className={'absolute top-0 blur-shape absolute w-full h-full'}>*/}
                  {/*</Image>*/}
              </div>
              <div className={'inline-block absolute w-[2.7vw] h-[2vw] left-[45.8vw] top-[35.1vw] z-40'}>
                  <Image src={'/images/arrow_horizontal.svg'} layout={'fill'}></Image>
              </div>
              <div className={'absolute blur-shape rounded-[0.4vw] left-[48.3vw] top-[32.4vw] w-[19.6vw] h-[7.5vw]'}>
                  <p className={'z-40 text-[1.4vw] text-center p-[1.7vw] absolute top-0 text-white font-desc font-light'}>Earn experience and token in battles</p>
                  {/*<Image src={'/images/AboutScreenShapes/2.svg'} layout={'fill'} className={'absolute top-0 blur-shape absolute w-full h-full'}></Image>*/}
              </div>
              <div className={'inline-block absolute w-[2.7vw] h-[2vw] left-[67.9vw] top-[36vw] z-40'}>
                  <Image src={'/images/arrow_horizontal.svg'} layout={'fill'}></Image>
              </div>
              <div className={'absolute blur-shape rounded-[0.4vw] right-[4.2vw] top-[32.7vw] w-[25.6vw] h-[7.5vw]'}>
                  <p className={'z-40 text-[1.4vw] text-center p-[1.7vw] absolute top-0 text-white font-desc font-light'}>Upgrade your equipment and buy more powerful items</p>
                  {/*<Image src={'/images/AboutScreenShapes/3.svg'} layout={'fill'} className={'absolute top-0 blur-shape absolute w-full h-full'}></Image>*/}
              </div>
              <div className={'inline-block absolute w-[2.7vw] h-[3vw] right-[10.3vw] top-[40vw] z-40'}>
                  <Image src={'/images/arrow_vertical.svg'} layout={'fill'}></Image>
              </div>
              <div className={'absolute blur-shape rounded-[0.4vw] right-[4.2vw] top-[43vw] w-[25.3vw] h-[9.5vw]'}>
                  <p className={'z-40 text-[1.4vw] text-center p-[1.7vw] absolute top-0 text-white font-desc font-light'}>Create a clan, build a castle to make an experience boost and other opportunites</p>
                  {/*<Image src={'/images/AboutScreenShapes/3.svg'} layout={'fill'} className={'absolute top-0 blur-shape absolute w-full h-full'}></Image>*/}
              </div>
              <div className={'rotate-180 inline-block absolute w-[2.7vw] h-[2vw] left-[67.9vw] top-[46.2vw] z-40'}>
                  <Image src={'/images/arrow_horizontal.svg'} layout={'fill'}></Image>
              </div>
              <div className={'absolute blur-shape rounded-[0.4vw] right-[32vw] top-[44.5vw] w-[19.7vw] h-[7.4vw]'}>
                  <p className={'z-40 text-[1.4vw] text-center p-[1.7vw] absolute top-0 text-white font-desc font-light'}>Trade equipment and tokens in the market</p>
                  {/*<Image src={'/images/AboutScreenShapes/3.svg'} layout={'fill'} className={'absolute top-0 blur-shape absolute w-full h-full'}></Image>*/}
              </div>
              <div className={'rotate-180 inline-block absolute w-[2.8vw] h-[2vw] left-[45.5vw] top-[47.4vw] z-40'}>
                  <Image src={'/images/arrow_horizontal.svg'} layout={'fill'}></Image>
              </div>
              <div className={'absolute blur-shape rounded-[0.4vw] left-[23vw] top-[43.2vw] w-[22.8vw] h-[9.4vw]'}>
                  <p className={'z-40 text-[1.4vw] text-center p-[1.7vw] absolute top-0 text-white font-desc font-light'}>Have fun and real Play-to-earn. No staking. No farming. Just gaming.</p>
                  {/*<Image src={'/images/AboutScreenShapes/3.svg'} layout={'fill'} className={'absolute top-0 blur-shape absolute w-full h-full'}></Image>*/}
              </div>
          </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
