import React from "react";
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from "../components/Navbar"
import Player from "../components/Player";
const myAccount: NextPage = () => {
  return (
      <div>
      <Head>
        <title>REON ARENA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
          <link
              rel="preload"
              href="/fonts/Danger/Another%20Danger%20Slanted.woff"
              as="font"
              crossOrigin=""
          />
          <link
              rel="preload"
              href="/fonts/Jost/Jost-Black.woff"
              as="font"
              crossOrigin=""
          />
      </Head>

      <main className={styles.main}>

          <Navbar></Navbar>

          {/*ARENA*/}

          <div className={' block bg-cover text-[10px] sm:text-[25px] lg:text-[30px] bg-[url(../public/images/account/account_bg.png)] relative w-[100vw] h-[112.5vw]'}>
              <Player></Player>
          </div>


      </main>

        <footer className={'bg-[#103643]'}>
            <div className={'w-full h-[12vw]'}>
                <div className={'w-[73%] left-[21%] top-[-2vw] relative h-full'}>
                    <div className={'inline-block w-[8.5vw] h-[8.5vw] absolute top-[30%] left-0'}>
                        <Image src={'/images/footer_logo.png'} layout={'fill'}></Image>
                    </div>
                    <a className={'tracking-[0.135em] font-title text-[1.5vw] top-[6.6vw] absolute text-reon left-[11vw]'} href={'/'}>MAIN</a>
                    <a className={'tracking-[0.135em] font-title text-[1.5vw] top-[6.6vw] absolute text-reon left-[17.5vw]'} href={'/arena'}>ARENA</a>
                    <a className={'tracking-[0.135em] font-title text-[1.5vw] top-[6.6vw] absolute text-reon left-[25.6vw]'} href={'/marketplace'}>MARKETPLACE</a>
                    <a className={'tracking-[0.135em] font-title text-[1.5vw] top-[6.6vw] absolute text-reon left-[39.6vw]'} href={'/tavern'}>TAVERN</a>
                    <a className={'tracking-[0.135em] font-title text-[1.5vw] top-[6.6vw] absolute text-reon left-[48.6vw]'} href={'/coming'}>MY ACCOUNT</a>
                    <div className={'inline-block absolute top-[6vw] left-[64.6vw] w-[3.6vw] h-[3.6vw]'}>
                        <Image src={'/images/twitter_button.png'} layout={'fill'}></Image>
                    </div>
                    <div className={'inline-block absolute top-[6vw] left-[68.9vw] w-[3.6vw] h-[3.6vw]'}>
                        <Image src={'/images/telegram_button.png'} layout={'fill'}></Image>
                    </div>
                    <div className={'inline-block absolute top-[6vw] left-[60.3vw] w-[3.6vw] h-[3.6vw]'}>
                        <Image src={'/images/mail_button.png'} layout={'fill'}></Image>
                    </div>
                </div>
            </div>

        </footer>
    </div>
  )
}

export default myAccount
