import React, { Component } from "react";
import type { NextPage } from 'next'
import Slider from "react-slick";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CenterMode from "../components/CenterSlider";
import SimpleSlider from "../components/CenterSlider";
import Navbar from "../components/Navbar"
import CenterSlider from "../components/CenterSlider";
import { motion } from 'framer-motion';


const Taverna: NextPage = () => {
    const settings = {
        className: "center",
        centerMode: true,
        infinite: true,
        centerPadding: "60px",
        slidesToShow: 3,
        speed: 500
    };
  return (
    <div className={styles.container}>
      <Head>
        <title>REON TAVERNA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
          <link
              rel="preload"
              href="/fonts/Danger/Another%20Danger%20Slanted.woff"
              as="font"
              crossOrigin=""
          />
          <link
              rel="preload"
              href="/fonts/Jost/Jost-Black.woff"
              as="font"
              crossOrigin=""
          />
      </Head>

      <main className={styles.main}>

          <Navbar></Navbar>

          {/*TAVERNA*/}

          <div className={' block bg-cover text-[10px] sm:text-[25px] lg:text-[30px] bg-[url(../public/images/bg_taverna.png)] relative w-[100vw] h-[58vw]'}>
              <motion.div className={'absolute top-0'} initial={'hidden'} animate={'visible'} variants={{
                  'hidden': {
                      opacity: 0
                  },
                  'visible': {
                      opacity: 1,
                      transition: {
                          delay: .4,
                          duration:1,
                      },
                  },
              }}><h1 className={'absolute inline-block left-[36vw] top-[4vw] text-reon text-[6.2vw] font-title'}>TAVERNA</h1></motion.div>
              <motion.div className={'absolute top-0'} initial={'hidden'} animate={'visible'} variants={{
                  'hidden':{
                      opacity:0,
                      x:-100,
                  },
                  'visible':{
                      opacity:1,
                      x:0,
                      transition:{
                          delay:1,
                          duration:1,
                      }
                  }
              }}><h3 className={'absolute inline-block font-desc text-white left-[59.7vw] top-[27vw] leading-[123%] w-[28.3vw] text-[1.34vw]'}>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </h3></motion.div>
              <motion.div className={'absolute top-0'} initial={'hidden'} animate={'visible'} variants={{
                  'hidden':{
                      opacity:0,
                      y:-50,
                  },
                  'visible':{
                      opacity:1,
                      y:0,
                      transition:{
                          delay:1.5,
                          ease:'easeIn',
                          duration:1,
                      }
                  }
              }}><h3 className={'absolute inline-block tracking-[-0.03em] font-jost font-bold text-white text-center left-[59.8vw] top-[20.6vw] bg-gold text-[4.4vw]'}>100<span className={'text-[4vw]'}>$</span></h3></motion.div>
              <motion.div className={'absolute top-0'} initial={'hidden'} animate={'visible'} variants={{
                  'hidden':{
                      opacity:0,
                  },
                  'visible':{
                      opacity:1,
                      transition:{
                          delay:2.5,
                          ease:'circIn',
                          duration:0.3,
                      }
                  }
              }}><button className={'z-50 rounded-[1vw] inline-block absolute left-[31.3vw] h-[6vw] w-[33.6vw] top-[43vw] gold-button'}><h2 className={'button-text font-title tracking-[0.13em] text-[3vw]'}>summon your hero</h2></button></motion.div>
              <motion.div className={'z-50 cursor-pointer inline-block absolute left-[23.8vw] top-[6.4vw] w-[5.3vw] h-[5.3vw]  rotate-180'} initial={'hidden'} animate={'visible'} variants={{
                  'hidden':{
                      opacity:0,
                  },
                  'visible':{
                      opacity:1,
                      transition:{
                          delay:0.5,
                          ease:'circIn',
                          duration:0.3,
                      }
                  }}}><a className={'cursor-pointer'} href={'/'}><Image className={'rotate-180 cursor-pointer'} src={'/images/goback_arrow.png'} layout={'fill'} /></a></motion.div>
              <motion.div className={'inline-block absolute left-[59.3vw] top-[4vw] w-[10vw] h-[10vw] rotate-180'} initial={'hidden'} animate={'visible'} variants={{
                  'hidden':{
                      opacity:0,
                  },
                  'visible':{
                      opacity:1,
                      transition:{
                          delay:0.5,
                          ease:'circIn',
                          duration:0.3,
                      }
                  }}}><Image className={'rotate-180'} src={'/images/reon_logo.png'} layout={'fill'} /></motion.div>
              <motion.div className={'inline-block absolute left-0 top-0 w-[100vw] h-[58vw] rotate-180'} initial="hidden"
                          whileInView={'visible'}

                          viewport={{once:true}}
                          transition={{ duration: 2, delay:0.3, ease:'easeInOut'}}
                          variants={{
                              visible: { opacity: 1, scale: 1, rotate:180 },
                              hidden: { opacity: 0, scale: 0.4, rotate:180 }
                          }}><Image className={'rotate-180'} src={'/images/portal.png'} layout={'fill'} /></motion.div>
          </div>


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Taverna
